//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub category_id: i64,
    pub category_name: String,
    pub parent_category_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_category::Entity")]
    ProductCategories,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentCategoryId",
        to = "Column::CategoryId"
    )]
    SelfRef,
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_category::Relation::Product.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::product_category::Relation::Category.def().rev())
    }
}

impl Related<Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SelfRef.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
