//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

// pub mod user;
// pub mod product;
// pub mod category;
// pub mod region;
// pub mod product_category;
// pub mod product_region;
