//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::category::Entity as Category;
pub use super::product::Entity as Product;
pub use super::product_category::Entity as ProductCategory;
pub use super::product_region::Entity as ProductRegion;
pub use super::region::Entity as Region;
pub use super::user::Entity as User;
